### ISSUE TITLE
Mobile optimized version of menus

### ISSUE THREAD

**Issue by gabrielhl** [zalando-incubator/solution-center-header#33]
On mobile, the line-height of the menu items is so large it makes it seem like each line is a separate item.  (see screenshot: terms & conditions, privacy policy, my account)

Additionally this horizontal design is not ideal for mobile and will start to break once we need more items.

I suggest we create a mobile optimized version of the menu, with bigger touch targets and a vertical design.

Current: 
![image](https://cloud.githubusercontent.com/assets/31034/16003672/264892aa-315e-11e6-8296-4db94369465d.png)

Target:
![image](https://cloud.githubusercontent.com/assets/31034/16003688/360bb726-315e-11e6-8436-454a209e235b.png)

Here's the CSS I used to create the screenshot:
```css
@media (max-width: 600px) {
    
    .solution-center-header .menu {
        display: block;
        margin: 0;
        width: 100%;
        box-shadow: 0 2px 8px rgba(0,0,0,.25)
    }

    .solution-center-header .menu__item {
        padding: 1.2rem;
        border-bottom: 1px solid #ededed;
    }

    .solution-center-header .menu__item:last-child {
        border-bottom: 0;
    }

    .solution-center-header .menu__link {
        line-height: 1.6rem;
        margin: 0;
    }
}
```
